[Query]
currentMatch = "Match.1"


[Match]

  [Match.1]
  currentGame = "Game.1"
  stats = ["SideStats.1", "SideStats.2"]


[Game]

  [Game.1]
  servingSide = "SIDE_A"

    [[Game.1.pointsWon]]
    count = 2
    side = "SIDE_A"

    [[Game.1.pointsWon]]
    count = 1
    side = "SIDE_B"


[SideStats]

  [SideStats.1]
  side = "SIDE_A"
  players = ["PlayerStats.1"]

  [SideStats.2]
  side = "SIDE_B"


[PlayerStats]

  [PlayerStats.1]
  [PlayerStats.1.aces]
  count = 2